---
- hosts: indieauth
  remote_user: ops
  sudo_user: indieauth
  sudo: yes

  vars:
    deploy_dir: "indieauth.com"
    deploy_repo: "https://github.com/aaronpk/IndieAuth.com.git"
    deploy_branch: "master"

  tasks:
    - name: ensure local bin directory
      file: 
        state: directory
        path: "/home/indieauth/bin"
        owner: "indieauth"
        group: "indieauth"

    - name: unpack ruby
      unarchive:
        src: "/tmp/{{ ruby.tarball }}"
        dest: "/home/indieauth"
        copy: no
        creates: "/home/indieauth/ruby-{{ ruby.version }}"

    - name: configure ruby
      command: "./configure --prefix=/home/indieauth"
      args:
        chdir: "/home/indieauth/ruby-{{ ruby.version }}"
        creates: "/home/indieauth/ruby-{{ ruby.version }}/Makefile"

    - name: build ruby
      command: "make"
      args:
        chdir: "/home/indieauth/ruby-{{ ruby.version }}"
        creates: "/home/indieauth/ruby-{{ ruby.version }}/ruby"

    - name: install ruby
      command: "make install"
      args:
        chdir: "/home/indieauth/ruby-{{ ruby.version }}"
        creates: "/home/indieauth/bin/ruby"

    - name: install bundler
      gem:
        name: bundler
        state: present
        executable: "/home/indieauth/bin/gem"

    - name: enable runit for indieauth
      file:
        src: "/etc/sv/indieauth"
        dest: "/etc/service/indieauth"
        state: link

    - name: deploy script
      template:
        src: templates/deploy.sh.j2
        dest: "/home/indieauth/deploy.sh"
        owner: "indieauth"
        group: "indieauth"
        mode: "0755"

    - name: deploy indieauth
      shell: "/home/indieauth/deploy.sh"
      args:
        executable: "/bin/bash"
        chdir: "/home/indieauth"

    - name: install gems
      shell: "/home/indieauth/.gem/ruby/2.2.0/bin/bundle install"
      args:
        executable: "/bin/bash"
        chdir: "/home/indieauth/indieauth.com"
